### ISSUE TITLE
router.register(["POST", "GET"], "/path", handler);

### ISSUE THREAD

**Issue by yunbookf** [litert/http.js#1]
thx.

And u r so handsome.

**Comment by fenying** [comment]
Nice idea.

So this should also applied to other handler register methods like `get`, `post`, `put`, etc, and even the middleware register method `use`.

Well, this will be achieved in next release.

**Comment by fenying** [comment]
Achieved in v0.2.2 (e4b61ce)

See here https://github.com/litert/http.js/releases/tag/v0.2.2
